apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: default-port
        volumeMounts:
        - name: stddata-vol
          mountPath: /data/db
        env:
        - name: MONGO_DATABASE
          value: stddata
      volumes:
      - name: stddata-vol
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    name: tcp
  selector:
    app: mongodb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: std-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: std-app
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: std-app
    spec:
      containers:
      - name: std-app
        image: vinothramesh/std-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: default-port
        env:
        - name: MONGO_URI
          value: mongodb

---

apiVersion: v1
kind: Service
metadata:
  name: std-app
  labels:
    app: std-app
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: std-app

